### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by LucasMahieu** [manelbaradad/munkres-tensorflow#2]
Hey, I don't succeed  to compile your work. 
Here are compilation error : 
do you have an idea ?

g++ -std=c++11 -shared hungarian.cc -o hungarian.so -fPIC -I$(TF_INC)
hungarian.cc: In lambda function:
hungarian.cc:20:40: error: cannot convert ‘tensorflow::shape_inference::ShapeHandle’ to ‘const tensorflow::shape_inference::Shape*’ in initialization
         const Shape* input = c->input(0);
                                        ^
In file included from hungarian.cc:4:0:
.../include/tensorflow/core/framework/shape_inference.h:91:3: error: ‘tensorflow::shape_inference::ShapeHandle::ShapeHandle(const tensorflow::shape_inference::Shape*)’ is private
   ShapeHandle(const Shape* shape) { ptr_ = shape; }
   ^
hungarian.cc:22:32: error: within this context
         if (!c->RankKnown(input)) {
                                ^
In file included from hungarian.cc:4:0:
.../include/tensorflow/core/framework/shape_inference.h:91:3: error: ‘tensorflow::shape_inference::ShapeHandle::ShapeHandle(const tensorflow::shape_inference::Shape*)’ is private
   ShapeHandle(const Shape* shape) { ptr_ = shape; }
   ^
hungarian.cc:28:47: error: within this context
         const int32 input_rank = c->Rank(input);
                                               ^
In file included from hungarian.cc:4:0:
.../include/tensorflow/core/framework/shape_inference.h:91:3: error: ‘tensorflow::shape_inference::ShapeHandle::ShapeHandle(const tensorflow::shape_inference::Shape*)’ is private
   ShapeHandle(const Shape* shape) { ptr_ = shape; }
   ^
hungarian.cc:32:46: error: within this context
             dims.emplace_back(c->Dim(input, i));
                                              ^
hungarian.cc:35:43: error: no matching function for call to ‘tensorflow::shape_inference::InferenceContext::MakeShape(std::vector<const tensorflow::shape_inference::Dimension*>&)’
         c->set_output(0, c->MakeShape(dims));
                                           ^
In file included from hungarian.cc:4:0:
.../include/tensorflow/core/framework/shape_inference.h:329:15: note: candidate: tensorflow::shape_inference::ShapeHandle tensorflow::shape_inference::InferenceContext::MakeShape(const std::vector<tensorflow::shape_inference::DimensionHandle>&)
   ShapeHandle MakeShape(const std::vector<DimensionHandle>& dims);
               ^
.../include/tensorflow/core/framework/shape_inference.h:329:15: note:   no known conversion for argument 1 from ‘std::vector<const tensorflow::shape_inference::Dimension*>’ to ‘const std::vector<tensorflow::shape_inference::DimensionHandle>&’
.../include/tensorflow/core/framework/shape_inference.h:330:15: note: candidate: tensorflow::shape_inference::ShapeHandle tensorflow::shape_inference::InferenceContext::MakeShape(std::initializer_list<tensorflow::shape_inference::DimensionOrConstant>)
   ShapeHandle MakeShape(std::initializer_list<DimensionOrConstant> dims);
               ^
.../include/tensorflow/core/framework/shape_inference.h:330:15: note:   no known conversion for argument 1 from ‘std::vector<const tensorflow::shape_inference::Dimension*>’ to ‘std::initializer_list<tensorflow::shape_inference::DimensionOrConstant>’
In file included from /usr/include/x86_64-linux-gnu/c++/5/bits/c++allocator.h:33:0,
                 from /usr/include/c++/5/bits/allocator.h:46,
                 from /usr/include/c++/5/string:41,
                 from /usr/include/c++/5/stdexcept:39,
                 from /usr/include/c++/5/array:38,
                 from /usr/include/c++/5/tuple:39,
                 from /usr/include/c++/5/functional:55,
                .../include/tensorflow/core/framework/op.h:19,
                 from hungarian.cc:2:
/usr/include/c++/5/ext/new_allocator.h: In instantiation of ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = const tensorflow::shape_inference::Dimension*; _Args = {tensorflow::shape_inference::DimensionHandle}; _Tp = const tensorflow::shape_inference::Dimension*]’:
/usr/include/c++/5/bits/alloc_traits.h:530:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = const tensorflow::shape_inference::Dimension*; _Args = {tensorflow::shape_inference::DimensionHandle}; _Tp = const tensorflow::shape_inference::Dimension*; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<const tensorflow::shape_inference::Dimension*>]’
/usr/include/c++/5/bits/vector.tcc:96:30:   required from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {tensorflow::shape_inference::DimensionHandle}; _Tp = const tensorflow::shape_inference::Dimension*; _Alloc = std::allocator<const tensorflow::shape_inference::Dimension*>]’
hungarian.cc:32:47:   required from here
/usr/include/c++/5/ext/new_allocator.h:120:4: error: cannot convert ‘tensorflow::shape_inference::DimensionHandle’ to ‘const tensorflow::shape_inference::Dimension*’ in initialization
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
    ^

**Comment by mbaradad** [comment]
Which version of tensorflow are you using? This isn't compatible with 1.0 (it was tested with 0.12). 
I have the code ready for 1.0 and I'll try to commit it tomorrow.

**Comment by LucasMahieu** [comment]
Ho great, it is for this reason, so.
Thanks a lot

-------------------------
Lucas MAHIEU
Lucas.mahieu@icloud.com

**Comment by mbaradad** [comment]
I've done the push. It should now work with 1.0 (and won't work with 0.12 with the current version).
